Repository Ollie-beep-bop/CodeHashira, pull requests merged in 2022-10, with the labels that each got.

#1 Steps to win SnakeLadder.java
  SnakeLadder.java
Labels: hactoberfest-accepted

#2 Radix-sort.cpp
  Radix-sort.cpp
Labels: hacktoberfest-accepted

#5 Creation and traversal of a Binary Tree
  Creation of a Binary Tree, Inorder, preorder & Postorder traversal.c
Labels: hacktoberfest-accepted

#4 Create Minimum cost path with l, r, u and d movements allowed
  Minimum cost path with l,r,u and d movements allowed
Labels: hacktoberfest-accepted

#7 Create StackUsingLinklist.c
  StackUsingLinklist.c
Labels: hacktoberfest-accepted

#8 Create prim's algo.cpp
  prim's algo.cpp
Labels: hacktoberfest-accepted

#9 Create Find equilibrium index of an array
  Find equilibrium index of an array
  Maximum Sum Circular Subarray
Labels: hacktoberfest-accepted

#10 Add files via upload
  qrcodeScanner.ipynb
Labels: hacktoberfest-accepted

#11 Hammingcode
  Heart_Disease_Prediction.ipynb
  Ocr.ipynb
  hammingcode.c
Labels: good first issue, hacktoberfest-accepted

#12 Interpolation Search
  Interpolation_search.c
Labels: hacktoberfest-accepted
